version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - staticcheck
        text: 'ST1000: at least one file in a package should have a package comment'
      - linters:
          - staticcheck
        text: 'ST1020: comment on exported function'
    paths:
      - test
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
